# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  spring-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # - name: Change directory to gradlew
    #   run: cd ./server/9in/

    - name: Grant Execute Permission For Gradlew & Build gradle
      run: |
        cd ./server/9in
        chmod +x gradlew
        ./gradlew build 
      
    # - name: Build with Gradle
    #   run: ./gradlew build 
    
    - name: Docker hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        
    - name: Docker image build
      run: |
        cd ./server/9in
        docker build -t ${{secrets.DOCKERHUB_ID}}/9uin-server .
      

    - name: Docker Hub push
      run: docker push ${{secrets.DOCKERHUB_ID}}/9uin-server 
    

    # - name: Stop exist images & Pull Docker image 
    #   run: |
    #     sudo docker rm -f $(docker ps -q) 2>/dev/null || true
    #     sudo docker pull ${{secrets.DOCKERHUB_ID}}/9uin-server
    #     cd ./server/9in
    #     docker-compose up -d
    #     sudo docker image prune -f
        
    #     # sudo docker rmi ${{secrets.DOCKERHUB_ID}}/9uin-server
    #     #docker run -d --name 9uin-server -p 8080:8080 ${{secrets.DOCKERHUB_ID}}/9uin-server
    #     # docker rmi 
    
    - name: Deploy to Instance
      uses: appleboy/ssh-action@v1.0.0     #가장 최신 버젼 appleboy 사용
      with:
        host: ${{secrets.GCP_HOST}}
        username: ${{secrets.GCP_USERNAME}}
        key: ${{secrets.GCP_PRIVATEKEY}}  
        script: |
          sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker pull ${{secrets.DOCKERHUB_ID}}/9uin-server
          sudo docker rm -f $(docker ps -qa) 2>/dev/null || true
          cd side_project/server/9in/
          sudo docker-compose up -d
          sudo docker image prune -f
          
      
      
        
   
      
      
      
      


